services:

  backend:
    build:
      context: ./backend
    container_name: spaceops-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: spaceops-frontend
    ports:
      - "3000:80"

    depends_on:
      - backend